name: Build FVSak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-fvs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build FVSak
      run: "../../bin/make FVSak.exe"
